### ISSUE TITLE
[Enigma] Копируем потоки правильно

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aracturat/nsudotnet#1]
> while (!reader.EndOfStream)

Николай, вот вы молодой, интеллигентный студент ФизФака, а копируете потоки друг в друга как... собсно, как молодой интеллигентный студент ФизФака.

Ради всего святого, найдите нормальный путь копирования потоков.

И на будущее - ваш шифровальщик правильно работает только с текстовыми файлами. А большинство приватной информации на земле, увы, в той или иной мере в binary.

В ходе устранения неправильного копирования потоков вы найдете решение и для проблемы из предыдущего абзаца.

Ну и заодно расскажите мне что не так, как надо, вот это все...

**Comment by Aracturat** [comment]
Я так понимаю, что надо использовать input.CopyTo(output)?
Еще есть вариант с 
   byte[] buffer = new byte[32768];
    int read;
    while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
    {
        output.Write (buffer, 0, read);
    }

**Comment by Aracturat** [comment]
А мой вариант не правилен тем, что если шифровать большой файл, то у меня может кончиться память, так как я весь файл в нее считаю.

**Comment by pavel-b-novikov** [comment]
> Еще есть вариант

Я по-моему во всеуслышание говорил что так делать не надо. И почему - тоже говорил.

Вариант с input.CopyTo правильный. Однако обоснование почему с Writer-ами не будет работать - в корне неверно. Вот попробуйте откатиться к предыдущей ревизии и зашифровать-расшифровать .exe своим шифровальщиком. И объясните мне наблюдаемые результаты.

**Comment by Aracturat** [comment]
Я просто думал, что проблема не в Writer, а в ReadLine(). Насчет Writer'ов подумаю.

**Comment by Aracturat** [comment]
Вместо SteamReader/StreamWriter надо было использовать BinaryReader/BinaryWriter, так как StreamReader предназначен для чтения текстовых данных.

**Comment by pavel-b-novikov** [comment]
"...добрым молодцам урок"
