### ISSUE TITLE
[Enigma] Делегаты

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aracturat/nsudotnet#2]
Я вценил подход с делегатом, но без понимания что к чему он может выстрелить в ногу.

Опишите в комментариях какие потенциальные проблемы вы видите в "делегатном" подходе, если шифровать потребуется не один файл, а несколько. Особенно параллельно.

**Comment by Aracturat** [comment]
Не нашел потенциальных проблем в делегатном подходе.

**Comment by pavel-b-novikov** [comment]
Ищите. Почитайте про замыкания.

2015-05-17 19:28 GMT+06:00 Nikolay Dozmorov notifications@github.com:

> Не нашел потенциальных проблем в делегатном подходе.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aracturat/nsudotnet/issues/2#issuecomment-102804357.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Aracturat** [comment]
Потенциальная проблема состоит в том, что они не потокобезопасны.

**Comment by pavel-b-novikov** [comment]
Чушь. Ищите дальше.
В лекциях об этом была речь.

17 мая 2015 г., 19:37 пользователь Nikolay Dozmorov <
notifications@github.com> написал:

> Потенциальная проблема состоит в том, что они не потокобезопасны.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aracturat/nsudotnet/issues/2#issuecomment-102804747.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Aracturat** [comment]
Но у меня не создается замыкания при создании делегата. Если бы были замыкания, то один поток мог изменить переменную, что попала в замыкание, и это было не безопасно.

**Comment by pavel-b-novikov** [comment]
Ой ли не создается?
Пойдем длинным путем.
Что такое замыкание?

17 мая 2015 г., 20:06 пользователь Nikolay Dozmorov <
notifications@github.com> написал:

> Но у меня не создается замыкании при создании делегата. Если бы были
> замыкания, то один поток мог изменить переменную, что попала в замыкание, и
> это было не безопасно.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aracturat/nsudotnet/issues/2#issuecomment-102806565.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Aracturat** [comment]
Я так понимаю, что тут
using (var inStream = new FileStream(inputFilename, FileMode.Open, FileAccess.Read))
using (var outStream = new FileStream(outputFilename, FileMode.OpenOrCreate, FileAccess.Write))
{
     outStream.SetLength(0);
     func.Invoke(inStream, outStream, algorythm);
}
создается замыкание на algorythm, и поэтому один поток может изменить algorythm, что повлияет  на algorythm в других потоках. А inStream и outStream каждый раз новые переменные, поэтому  на них это не влияет.

**Comment by pavel-b-novikov** [comment]
Николай, что такое замыкание?

17 мая 2015 г., 20:31 пользователь Nikolay Dozmorov <
notifications@github.com> написал:

> Я так понимаю, что тут
> 
> func.Invoke(inStream, outStream, algorythm);
> создается замыкание на algorythm, и поэтому один поток может изменить
> algorythm, что повлияет на algorythm в других потоках.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aracturat/nsudotnet/issues/2#issuecomment-102808738.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Aracturat** [comment]
Мы использовали локальную переменную
В делегате, который вызывается в другом месте
Эта ситуация называется «замыкание» -«closure». (c) лекции.

**Comment by Aracturat** [comment]
А вообще, я же не просто так это заявлял. Я написал тестовую программу:
https://gist.github.com/Aracturat/368020964e82e396579d
И в ней я в одном потоке меняю содержимое Algorithm, а в другом потоке она тоже меняется.

**Comment by pavel-b-novikov** [comment]
Да тут не столько в многопоточности дело, сколько в циклах по многим файлам
блин.

17 мая 2015 г., 20:53 пользователь Nikolay Dozmorov <
notifications@github.com> написал:

> А вообще, я же не просто так это заявлял. Я написал тестовую программу:
> https://gist.github.com/Aracturat/368020964e82e396579d
> И в ней я в одном потоке меняю содержимое Algorithm, а в другом потоке она
> тоже меняется.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aracturat/nsudotnet/issues/2#issuecomment-102811115.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Aracturat** [comment]
Я понимаю, что из-за того, что я бы использовал одну переменную для цикла по многим файлам, то у меня бы могли возникнуть проблемы из-за того, что в результате все делегаты бы запустились от одного параметра. Но так как у меня бы возникала конструкция:

``` C#
foreach(int i = 0; i < inputFilenames.Length; i++) {
    using (var inStream = new FileStream(inputFilenames[i], FileMode.Open, FileAccess.Read))
    using (var outStream = new FileStream(outputFilenames[i], FileMode.OpenOrCreate, FileAccess.Write))
    {
          func.Invoke(inStream, outStream, algorythm);
    }
}
```

То в данном случае такой проблемы нет. Так как я каждый раз создаю новые потоки (FileStream), и уже они захватываются в замыкание. А вот с алгоритмом да, может быть проблема.

**Comment by pavel-b-novikov** [comment]
Принято. Зачет у Семена получите.

18 мая 2015 г., 9:25 пользователь Nikolay Dozmorov <notifications@github.com

> написал:
> 
> Я понимаю, что из-за того, что я бы использовал одну переменную для цикла
> по многим файлам, то у меня бы могли возникнуть проблемы из-за того, что в
> результате все делегаты бы запустились от одного параметра. Но так как у
> меня бы возникала конструкция:
> 
> foreach(int i = 0; i < inputFilenames.Length; i++) {
>     using (var inStream = new FileStream(inputFilenames[i], FileMode.Open, FileAccess.Read))
>     using (var outStream = new FileStream(outputFilenames[i], FileMode.OpenOrCreate, FileAccess.Write))
>     {
>           func.Invoke(inStream, outStream, algorythm);
>     }
> }
> 
> То в данном случае такой проблемы нет. Так как я каждый раз создаю новые
> потоки (FileStream), и уже они захватываются в замыкание. А вот с
> алгоритмом да, может быть проблема.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aracturat/nsudotnet/issues/2#issuecomment-102908980.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447
