### ISSUE TITLE
[JsonSerializer] Reflection

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aracturat/nsudotnet#3]
Я закрою глаза на странноватое использование рекурсии в задаче, но расскажите мне вот что.

Какие свойства возвращает GetProperties (в смысле он возвращает далеко не все) и как его заставить возвращать приватные статические свойства?

**Comment by Aracturat** [comment]
А что странноватого в использовании рекурсии? У нас же один класс может содержать другой класс, и их нужно всех сериализовать.

**Comment by Aracturat** [comment]
Он возвращает  все открытые свойства. Необходимо использовать GetProperties(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static) для возвращения приватных статических свойств.

**Comment by pavel-b-novikov** [comment]
Рекурсия сама по себе не странна. Вы её организовали крайне странно.
Ответ неверный, кстати. Нам нужны только статические поля, а не вообще все.

**Comment by pavel-b-novikov** [comment]
(случайно тыкнул на "закрыть")

**Comment by Aracturat** [comment]
Нужно использовать и, а не или?
GetProperties(BindingFlags.NonPublic & BindingFlags.Instance & BindingFlags.Static);

**Comment by pavel-b-novikov** [comment]
(facepalm)
Думаем дальше, дальше думаем...

**Comment by Aracturat** [comment]
Так. Я понял, что там все таки "|")). 
Еще вариант, что BindingFlags.Instance не нужен.
GetProperties(BindingFlags.NonPublic | BindingFlags.Static)

**Comment by pavel-b-novikov** [comment]
Коля, заниматься перебором вариантов, при сдачи задачи мне - идея плохая :)
Студию, блин, откройте, да проверьте.

**Comment by Aracturat** [comment]
Ответ.
Если GetProperties(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static), то возвращает все статические свойства.
Если GetProperties(BindingFlags.NonPublic | BindingFlags.Static), то только приватные статические свойства.
Если GetProperties(), то все открытые свойства.

**Comment by pavel-b-novikov** [comment]
Окей, на том и порешим
